# Generated by Django 4.0.4 on 2022-05-11 19:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GiftCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("initial_amount", models.IntegerField(default=100)),
                ("current_amount", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="GiftCardLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField(default=100)),
                (
                    "order_number",
                    models.IntegerField(
                        default=uuid.UUID("53a05f14-d164-11ec-bdba-003676549075")
                    ),
                ),
                (
                    "gift_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.giftcards"
                    ),
                ),
            ],
        ),
    ]
