# Generated by Django 4.0.4 on 2022-05-11 21:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcardlogs",
            name="order_number",
            field=models.IntegerField(
                default=uuid.UUID("bc691769-d16e-11ec-a522-003676549075")
            ),
        ),
    ]
