# Generated by Django 4.0.4 on 2022-05-12 23:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_giftcardlogs_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcardlogs",
            name="amount",
        ),
        migrations.AddField(
            model_name="giftcardlogs",
            name="used_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="giftcardlogs",
            name="order_number",
            field=models.IntegerField(
                default=uuid.UUID("acb29e31-d249-11ec-bce1-e0d55e8832c4")
            ),
        ),
    ]
