# Generated by Django 4.0.4 on 2022-05-12 23:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_giftcardlogs_amount_giftcardlogs_used_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcardlogs",
            name="order_number",
            field=models.CharField(
                default=uuid.UUID("a9c57778-d24a-11ec-b3bd-e0d55e8832c4"),
                max_length=255,
            ),
        ),
    ]
