# Generated by Django 4.0.4 on 2022-05-12 23:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_giftcardlogs_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcardlogs",
            name="order_number",
            field=models.CharField(
                default=uuid.UUID("ad06a8f9-d24a-11ec-80e8-e0d55e8832c4"),
                max_length=255,
            ),
        ),
    ]
